CONFIG_STDOUT_CONSOLE=n
CONFIG_MP_MAX_NUM_CPUS=1

CONFIG_POSIX_AEP_CHOICE_BASE=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_DYNAMIC_THREAD=y

CONFIG_SYS_THREAD_THREAD_MIN=6
CONFIG_SYS_THREAD_STACK_MIN=6
CONFIG_SYS_THREAD_MUTEX_MIN=6

#Enable thread awareness for debugging tools supporting it
CONFIG_DEBUG_THREAD_INFO=y

#This is necessary to ensure that console output is comparable to the native variant.
CONFIG_POSIX_NON_PORTABLE=y

# For pthread_setschedparam()
CONFIG_POSIX_THREAD_PRIORITY_SCHEDULING=y
