# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  # zephyr-keep-sorted-start re(^\s+\- name:)
  projects:
    - name: busybox
      url: https://github.com/cfriedt/busybox
      revision: 15666f3e9a0b54305cec1b01f34bc5b2a1794e74
      path: modules/lib/busybox
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.5.0-rc1
      import:
        name-allowlist:
          - cmsis_6
          - fatfs
          - hostap
          - littlefs
          - mbedtls
          - picolibc
          - tf-psa-crypto
          - zcbor
  # zephyr-keep-sorted-stop

  self:
    path: modules/lib/posix
