/*
 * SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

#include <sys/socket.h>

#include <zephyr/net/net_ip.h>
#include <zephyr/net/socket.h>
#include <zephyr/sys/util.h>

BUILD_ASSERT(SOCK_STREAM == ZSOCK_TYPE_STREAM);
BUILD_ASSERT(SOCK_DGRAM == ZSOCK_TYPE_DGRAM);
BUILD_ASSERT(SOCK_RAW == ZSOCK_TYPE_RAW);
BUILD_ASSERT(AF_INET == ZSOCK_AF_INET);
BUILD_ASSERT(AF_INET6 == ZSOCK_AF_INET6);
BUILD_ASSERT(AF_UNIX == ZSOCK_AF_UNIX);
BUILD_ASSERT(AF_CAN == ZSOCK_AF_CAN);
BUILD_ASSERT(AF_PACKET == ZSOCK_AF_PACKET);
BUILD_ASSERT(AF_NET_MGMT == ZSOCK_AF_NET_MGMT);
BUILD_ASSERT(SOL_SOCKET == ZSOCK_SOL_SOCKET);
BUILD_ASSERT(SO_REUSEADDR == ZSOCK_SO_REUSEADDR);
BUILD_ASSERT(SOMAXCONN == ZSOCK_SOMAXCONN);
BUILD_ASSERT(SHUT_RD == ZSOCK_SHUT_RD);
BUILD_ASSERT(SHUT_WR == ZSOCK_SHUT_WR);
BUILD_ASSERT(SHUT_RDWR == ZSOCK_SHUT_RDWR);
BUILD_ASSERT(MSG_CTRUNC == ZSOCK_MSG_CTRUNC);
BUILD_ASSERT(MSG_PEEK == ZSOCK_MSG_PEEK);
BUILD_ASSERT(MSG_TRUNC == ZSOCK_MSG_TRUNC);
BUILD_ASSERT(MSG_DONTWAIT == ZSOCK_MSG_DONTWAIT);
BUILD_ASSERT(MSG_WAITALL == ZSOCK_MSG_WAITALL);

int socket(int family, int type, int proto)
{
	return zsock_socket(family, type, proto);
}
