#!/usr/bin/env python3
#
# Copyright (c) 2026, Friedt Professional Engineering Services, Inc.
#
# SPDX-License-Identifier: Apache-2.0
"""
Generate the Linux system call surface of the kernel compatibility layer.

Two steps, so that a build needs nothing but this script and syscalls.json:

  update   Rebuild syscalls.json (checked in beside this script) from the
           system-calls package (https://github.com/hrw/syscalls-table) and a
           Linux source tree of the same version:

             pip install system-calls
             python3 gen_linux_syscalls.py update --linux-src /path/to/linux

  emit     Write one architecture's files from syscalls.json, as the build does
           at configure time:

             python3 gen_linux_syscalls.py emit --arch x86_64 --out DIR

           DIR/syscalls.tbl                        '<zephyr syscall name> <linux number>'
                                                   lines, the ID reservation gen_syscalls.py
                                                   consumes
           DIR/include/zephyr/kcl/linux/syscalls.h one __syscall declaration per system call
           DIR/syscall_vrfy.c                      verifiers: tracing hooks around the implementation,
                                                   and the marshaller includes
           DIR/syscall_defaults.c                  weak implementations returning -ENOSYS

Linux types are mapped to zkcl_linux_* names declared by
<zephyr/kcl/linux/types.h>; 'update --list-types' prints what that header has to
provide.
"""

import json

import argparse
import os
import re
import sys

ARCHES = ["x86_64", "arm64", "riscv64", "riscv32", "arm", "i386"]

# name -> Linux table (relative to the source tree) and the ABI columns that apply
TABLES = {
    "x86_64": ("arch/x86/entry/syscalls/syscall_64.tbl", {"common", "64"}),
    "i386": ("arch/x86/entry/syscalls/syscall_32.tbl", {"i386"}),
    "arm": ("arch/arm/tools/syscall.tbl", {"common", "eabi"}),
    "arm64": ("scripts/syscall.tbl", None),
    "riscv64": ("scripts/syscall.tbl", None),
    "riscv32": ("scripts/syscall.tbl", None),
}

PROTOTYPE_HEADERS = [
    "include/linux/syscalls.h",
    "arch/x86/include/asm/syscalls.h",
    "arch/riscv/include/asm/syscall.h",
]

# entry points defined with SYSCALL_DEFINE in .c files, or otherwise not declared
EXTRA_PROTOTYPES = {
    "mmap": "unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, "
    "unsigned long fd, unsigned long off",
    "mmap2": "unsigned long addr, unsigned long len, unsigned long prot, unsigned long flags, "
    "unsigned long fd, unsigned long pgoff",
    "rt_sigreturn": "void",
    "sigreturn": "void",
    "ni_syscall": "void",
    # x86
    "arch_prctl": "int option, unsigned long arg2",
    "modify_ldt": "int func, void __user *ptr, unsigned long bytecount",
    "iopl": "unsigned int level",
    "set_thread_area": "struct user_desc __user *u_info",
    "get_thread_area": "struct user_desc __user *u_info",
    "vm86old": "struct vm86_struct __user *user_vm86",
    "vm86": "unsigned long cmd, unsigned long arg",
    # arm
    "arm_fadvise64_64": "int fd, int advice, loff_t offset, loff_t len",
    "cacheflush": "unsigned long start, unsigned long end, int flags",
    "set_tls": "unsigned long val",
    "get_tls": "void",
    "breakpoint": "void",
    "usr26": "void",
    "usr32": "void",
}

# system calls numbered beyond this are architecture-private ranges (arm 0x0f0000)
MAX_NUMBER = 1024

C_TYPES = {
    "void", "char", "short", "int", "long", "unsigned", "signed", "float", "double",
    "unsigned char", "unsigned short", "unsigned int", "unsigned long", "long long",
    "unsigned long long", "size_t", "uintptr_t", "intptr_t",
    "uint8_t", "uint16_t", "uint32_t", "uint64_t", "int8_t", "int16_t", "int32_t", "int64_t",
}

# Linux kernel scalar typedefs with a C equivalent of the same width on every arch
SCALAR_TYPES = {
    "u8": "uint8_t", "__u8": "uint8_t", "u16": "uint16_t", "__u16": "uint16_t",
    "u32": "uint32_t", "__u32": "uint32_t", "s32": "int32_t", "__s32": "int32_t",
    "u64": "uint64_t", "__u64": "uint64_t", "s64": "int64_t", "__s64": "int64_t",
}

SYSCALL_PREFIX = "zkcl_linux_syscall_"

HEADER = """/*
 * SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/* Generated by subsys/kcl/linux/gen_linux_syscalls.py for {arch} (Linux {version}). */
"""


def parse_prototypes(paths):
    protos = {}
    decl = re.compile(r"asmlinkage\s+long\s+sys_(\w+)\s*\(([^;]*?)\)\s*;", re.S)

    for path in paths:
        with open(path) as fp:
            text = fp.read()
        text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
        for m in decl.finditer(text):
            name, args = m.group(1), " ".join(m.group(2).split())
            protos.setdefault(name, args)

    for name, args in EXTRA_PROTOTYPES.items():
        protos.setdefault(name, args)

    return protos


def parse_table(path, abis):
    """{syscall name: entry point} of one Linux syscall table."""
    entries = {}

    with open(path) as fp:
        for line in fp:
            line = line.split("#", 1)[0].split()
            if len(line) < 3:
                continue
            _, abi, name = line[:3]
            entry = line[3] if len(line) > 3 else ""
            if (abis is not None) and (abi not in abis):
                continue
            entries.setdefault(name, entry)

    return entries


class Param:
    def __init__(self, text, index):
        text = re.sub(r"\b__user\b", "", text)
        text = re.sub(r"\b__kernel_", "", text)
        text = " ".join(text.split())
        m = re.match(r"^(.*?)\s*((?:\*\s*(?:const\s*)?)*)\s*(\w+)?$", text)
        assert m, text
        base, stars, name = m.group(1), m.group(2), m.group(3)
        if name and (name in C_TYPES or base == ""):
            # unnamed parameter: the "name" is the type's last word
            base, name = f"{base} {name}".strip(), None
        if base.endswith("*"):
            stars, base = base[base.index("*"):] + stars, base[: base.index("*")].strip()
        self.const = base.startswith("const ")
        base = base[6:] if self.const else base
        self.stars = " ".join(stars.split()).replace("* const", "*const")
        self.name = name or f"arg{index}"
        self.base = base.strip()

    def zephyr_type(self):
        base = self.base
        words = base.split()
        if words[0] == "enum":
            base = "int"
        elif words[0] in ("struct", "union"):
            base = f"{words[0]} zkcl_linux_{words[1].lstrip('_')}"
        elif base in C_TYPES:
            pass
        elif base in SCALAR_TYPES:
            base = SCALAR_TYPES[base]
        else:
            base = "zkcl_linux_" + base.lstrip("_")
        return ("const " if self.const else "") + base + (" " + self.stars if self.stars else "")

    def declaration(self):
        t = self.zephyr_type()
        return t + ("" if t.endswith("*") else " ") + self.name


def parse_params(args):
    if args.strip() in ("", "void"):
        return []
    params = []
    depth = 0
    cur = ""
    for c in args:
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        if c == "," and depth == 0:
            params.append(cur)
            cur = ""
        else:
            cur += c
    params.append(cur)
    return [Param(p, i + 1) for i, p in enumerate(params)]


def generic_params():
    return [Param(f"unsigned long arg{i}", i) for i in range(1, 7)]


def syscall_table(arch, table, protos, linux_numbers):
    """{name: (number, [Param], known_prototype)} for one architecture."""
    result = {}
    for name, number in sorted(linux_numbers.items(), key=lambda kv: kv[1]):
        if number >= MAX_NUMBER:
            print(f"{arch}: skipping {name} ({number:#x}): architecture-private range",
                  file=sys.stderr)
            continue
        entry = table.get(name, "")
        func = entry[4:] if entry.startswith("sys_") else ""
        args = protos.get(func) if func else None
        if args is None:
            args = protos.get(name)
        if args is None:
            params, known = generic_params(), False
        else:
            params, known = parse_params(args), True
        result[name] = (number, params, known)
    return result


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fp:
        fp.write(text)


def emit_arch(out, arch, data):
    """Write one architecture's files from the syscalls.json contents."""
    version = data["version"]
    guard = f"ZEPHYR_KCL_LINUX_{arch.upper()}_SYSCALLS_H_"
    head = HEADER.format(arch=arch, version=version)
    calls = sorted(
        ((name, rec["nr"][arch], rec["params"], not rec.get("raw", False))
         for name, rec in data["syscalls"].items() if arch in rec["nr"]),
        key=lambda c: c[1],
    )

    structs = set()
    for _, _, params, _ in calls:
        for p in params:
            words = p.replace("const ", "").split()
            if words[0] in ("struct", "union"):
                structs.add(f"{words[0]} {words[1]}")
    structs = sorted(structs)

    tbl = [f"# {SYSCALL_PREFIX}<name> <Linux {arch} number>: gen_syscalls.py --reserve input\n"]
    hdr = [head, f"\n#ifndef {guard}\n#define {guard}\n\n#include <stddef.h>\n#include <stdint.h>\n",
           "#include <zephyr/kcl/linux/types.h>\n#include <zephyr/sys/util_macro.h>\n\n"
           "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"]
    hdr.extend(f"{s_};\n" for s_ in structs)
    hdr.append("\n/* ZKCL_LINUX_SYSCALL_<name>: 1 when the call is on and this architecture has it */\n")
    present = {name for name, _, _, _ in calls}
    for name in sorted(data["syscalls"]):
        if name in present:
            hdr.append(f"#define ZKCL_LINUX_SYSCALL_{name} "
                       f"IS_ENABLED(CONFIG_KCL_LINUX_SYSCALL_{name.upper()})\n")
        else:
            hdr.append(f"#define ZKCL_LINUX_SYSCALL_{name} 0\n")
    hdr.append("\n")
    vrfy = [head, "\n#include <zephyr/kernel.h>\n#include <zephyr/kcl/linux/syscalls.h>\n"
            "#include <zephyr/internal/syscall_handler.h>\n"
            "#include <zephyr/tracing/tracing_syscall.h>\n\n#include \"kcl_linux.h\"\n\n"]
    defaults = [head, "\n#include <errno.h>\n#include <zephyr/kernel.h>\n"
                "#include <zephyr/kcl/linux/syscalls.h>\n\n"]

    for name, number, params, known in calls:
        func = SYSCALL_PREFIX + name
        names = [p.split()[-1].lstrip("*") for p in params]
        decl = ", ".join(params) or "void"
        call = ", ".join(names)
        tbl.append(f"{func} {number}\n")
        hdr.append(f"#define ZKCL_LINUX_NR_{name} {number}\n")
        if not known:
            hdr.append("/* no prototype in the Linux headers used: the raw argument words */\n")
        hdr.append(f"__syscall long {func}({decl});\n\n")
        trace_args = "".join(f", {n}" for n in names)
        vrfy.append(f"static inline long z_vrfy_{func}({decl})\n{{\n\tlong ret;\n\n"
                    f"\tsys_port_trace_syscall_enter(K_SYSCALL_{func.upper()}, {func}{trace_args});\n"
                    f"\tret = zkcl_linux_result(z_impl_{func}({call}));\n"
                    f"\tsys_port_trace_syscall_exit(K_SYSCALL_{func.upper()}, {func}{trace_args}, ret);\n\n"
                    f"\treturn ret;\n}}\n"
                    f"#include <zephyr/syscalls/{func}_mrsh.c>\n\n")
        unused = "".join(f"\tARG_UNUSED({n});\n" for n in names)
        defaults.append(f"__weak long z_impl_{func}({decl})\n{{\n{unused}\treturn -ENOSYS;\n}}\n\n")

    hdr.append("#ifdef __cplusplus\n}\n#endif\n\n#include <zephyr/syscalls/syscalls.h>\n\n"
               f"#endif /* {guard} */\n")

    write(os.path.join(out, "syscalls.tbl"), "".join(tbl))
    write(os.path.join(out, "include", "zephyr", "kcl", "linux", "syscalls.h"), "".join(hdr))
    write(os.path.join(out, "syscall_vrfy.c"), "".join(vrfy))
    write(os.path.join(out, "syscall_defaults.c"), "".join(defaults))


def update(args):
    """Rebuild syscalls.json from the system-calls package and a Linux tree."""
    try:
        import system_calls
    except ImportError:
        sys.exit("pip install system-calls (https://github.com/hrw/syscalls-table)")

    hrw = system_calls.syscalls()
    protos = parse_prototypes(
        p for p in (os.path.join(args.linux_src, h) for h in PROTOTYPE_HEADERS)
        if os.path.exists(p)
    )
    syscalls = {}
    typedefs = set()

    for arch in ARCHES:
        table_path, abis = TABLES[arch]
        table = parse_table(os.path.join(args.linux_src, table_path), abis)
        calls = syscall_table(arch, table, protos, hrw.load_arch_table(arch))
        for name, (number, params, known) in calls.items():
            rec = syscalls.setdefault(name, {"params": [p.declaration() for p in params],
                                             "nr": {}})
            if not known:
                rec["raw"] = True
            rec["nr"][arch] = number
            typedefs |= {
                p.base.lstrip("_") for p in params
                if p.base not in C_TYPES and p.base not in SCALAR_TYPES
                and p.base.split()[0] not in ("struct", "union", "enum")
            }
        unknown = [n for n, (_, _, known) in calls.items() if not known]
        print(f"{arch}: {len(calls)} system calls, {len(unknown)} without prototype: "
              f"{' '.join(unknown)}")

    lines = [f'{json.dumps(name)}: {json.dumps(syscalls[name], separators=(",", ":"))}'
             for name in sorted(syscalls)]
    text = ('{\n  "version": ' + json.dumps(hrw.linux_version) + ',\n  "arches": '
            + json.dumps(ARCHES) + ',\n  "syscalls": {\n    '
            + ",\n    ".join(lines) + "\n  }\n}\n")
    write(args.json, text)
    if args.list_types:
        print("typedefs needed in types.h: " + " ".join(sorted(typedefs)))


def emit(args):
    with open(args.json) as fp:
        data = json.load(fp)
    if args.arch not in data["arches"]:
        sys.exit(f"{args.json} has no {args.arch} table")
    emit_arch(args.out, args.arch, data)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    up = sub.add_parser("update", help="rebuild syscalls.json")
    up.add_argument("--linux-src", required=True, help="Linux source tree (headers, tables)")
    up.add_argument("--json", default=os.path.join(here, "syscalls.json"))
    up.add_argument("--list-types", action="store_true",
                    help="print the zkcl_linux_* typedefs the declarations need")
    up.set_defaults(func=update)
    em = sub.add_parser("emit", help="write one architecture's files")
    em.add_argument("--arch", required=True, choices=ARCHES)
    em.add_argument("--json", default=os.path.join(here, "syscalls.json"))
    em.add_argument("--out", required=True, help="directory to write into")
    em.set_defaults(func=emit)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
