#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
"""Pack JSON files into self-describing shell archives ("shellballs").

A shellball is a plain-text POSIX shell script with the JSON payload
embedded as base64 text, so large JSON snapshots stay diff-friendly text
files in git while taking a fraction of the space. Payloads at or above
the compression threshold are maximally compressed with the best of the
codecs available in the Python standard library (lzma/xz, bz2, gzip);
smaller payloads are embedded uncompressed (base64 only), recorded in the
embedded PN_COMPRESSION variable.

The generated script is self-describing and self-verifying::

    sh file.json.sh help      # list commands
    sh file.json.sh cat       # decode the JSON to stdout
    sh file.json.sh extract   # decode into a temporary directory
    sh file.json.sh query .a  # jq query against the decoded JSON
    sh file.json.sh commit    # commit the data was collected from
    sh file.json.sh tools     # decode pipeline + tools it requires
    sh file.json.sh info      # all embedded metadata
    sh file.json.sh verify    # check payload against embedded sha256

``tools`` prints the exact decode pipeline (e.g. ``base64 -d | xz -dc``)
so a platform can test the commands before relying on them.

Every ``pack`` run self-tests the composed shellball (cat round-trip,
verify, extract, tools; query when jq is available) before it is written
to its final destination.

``unpack`` decodes a shellball from Python without invoking a shell, for
consumers like scripts/doc/posix_metrics.py and CI jobs.
"""

from __future__ import annotations

import argparse
import base64
import bz2
import gzip
import hashlib
import json
import lzma
import os
import re
import shutil
import string
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

DEFAULT_MIN_COMPRESS_SIZE = 1024

# codec name -> (python compressor, shell decompress command, required tool)
CODECS = {
    "xz": (lambda b: lzma.compress(b, preset=9 | lzma.PRESET_EXTREME), "xz -dc", "xz"),
    "bzip2": (lambda b: bz2.compress(b, 9), "bzip2 -dc", "bzip2"),
    "gzip": (lambda b: gzip.compress(b, 9, mtime=0), "gzip -dc", "gzip"),
    "none": (lambda b: b, "cat", "cat"),
}

PAYLOAD_MARKER = "__JSONBALL_PAYLOAD__"


class ShellTemplate(string.Template):
    """string.Template with an @ delimiter so shell's $ needs no escaping."""

    delimiter = "@"


TEMPLATE = ShellTemplate(
    """\
#!/bin/sh
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
#
# @name -- JSON shellball generated by scripts/ci/jsonball.py; do not edit.
# Regenerate with: python3 scripts/ci/jsonball.py pack <input.json>
#
# The JSON payload is embedded below the @marker marker as base64 text
# (compression: @compression). Run with no arguments or "help" for usage.

set -eu

PN_NAME="@name"
PN_COMPRESSION="@compression"
PN_DECODE_CMD="base64 -d | @decompress"
PN_TOOLS="sed base64 @tool"
PN_SHA256="@sha256"
PN_SIZE=@size
PN_ENCODED_SIZE=@encoded_size
PN_MIN_COMPRESS_SIZE=@min_compress_size
PN_COMMIT="@commit"
PN_CREATED_AT="@created_at"

payload() {
	sed -e '1,/^@marker$/d' "$0"
}

decode() {
	payload | base64 -d | @decompress
}

usage() {
	cat <<EOF
usage: sh $0 <command> [args]

$PN_NAME: self-extracting JSON archive ($PN_SIZE bytes of JSON,
$PN_ENCODED_SIZE bytes encoded, compression: $PN_COMPRESSION).

commands:
  cat            decode the JSON to stdout
  extract [DIR]  decode to DIR (default: a new temporary directory);
                 prints the path of the extracted file
  query EXPR     run "jq EXPR" against the decoded JSON (requires jq)
  commit         print the commit the data was collected from
  created        print the collection timestamp
  sha256         print the expected sha256 of the decoded JSON
  tools          print the decode pipeline and the tools it requires
  info           print all embedded metadata
  verify         decode and check against the embedded sha256
  help           show this help
EOF
}

cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
cat)
	decode
	;;
extract)
	dir="${1:-$(mktemp -d)}"
	mkdir -p "$dir"
	decode > "$dir/$PN_NAME"
	echo "$dir/$PN_NAME"
	;;
query)
	decode | jq "$@@"
	;;
commit)
	echo "$PN_COMMIT"
	;;
created)
	echo "$PN_CREATED_AT"
	;;
sha256)
	echo "$PN_SHA256"
	;;
tools)
	echo "decode pipeline: sed -e '1,/^@marker$/d' $0 | $PN_DECODE_CMD"
	echo "required tools: $PN_TOOLS"
	;;
info)
	echo "name: $PN_NAME"
	echo "compression: $PN_COMPRESSION"
	echo "decode: $PN_DECODE_CMD"
	echo "tools: $PN_TOOLS"
	echo "sha256: $PN_SHA256"
	echo "size: $PN_SIZE"
	echo "encoded-size: $PN_ENCODED_SIZE"
	echo "min-compress-size: $PN_MIN_COMPRESS_SIZE"
	echo "commit: $PN_COMMIT"
	echo "created-at: $PN_CREATED_AT"
	;;
verify)
	actual=$(decode | sha256sum | cut -d' ' -f1)
	if [ "$actual" = "$PN_SHA256" ]; then
		echo "OK: $PN_NAME sha256 $actual"
	else
		echo "FAIL: $PN_NAME sha256 $actual != $PN_SHA256" >&2
		exit 1
	fi
	;;
help | *)
	usage
	;;
esac
exit 0
@marker
@payload
"""
)


def _provenance(data: bytes) -> tuple[str, str]:
    """Best-effort (commit, created_at) from a JSON payload's provenance."""
    try:
        doc = json.loads(data)
    except ValueError:
        return "", ""
    prov = doc.get("provenance", doc) if isinstance(doc, dict) else {}
    if not isinstance(prov, dict):
        return "", ""
    commit = str(prov.get("commit", "") or "")
    created = str(prov.get("created_at", "") or "")
    return commit, created


def compose(data: bytes, name: str, min_compress_size: int) -> str:
    if len(data) < min_compress_size:
        codec = "none"
        blob = data
    else:
        candidates = {key: CODECS[key][0](data) for key in ("xz", "bzip2", "gzip")}
        codec = min(candidates, key=lambda k: len(candidates[k]))
        blob = candidates[codec]
    _, decompress, tool = CODECS[codec]
    commit, created_at = _provenance(data)
    payload = "\n".join(textwrap.wrap(base64.b64encode(blob).decode("ascii"), 76))
    return TEMPLATE.substitute(
        name=name,
        compression=codec,
        decompress=decompress,
        tool=tool,
        sha256=hashlib.sha256(data).hexdigest(),
        size=len(data),
        encoded_size=len(payload),
        min_compress_size=min_compress_size,
        commit=commit,
        created_at=created_at,
        marker=PAYLOAD_MARKER,
        payload=payload,
    )


def parse_ball(text: str) -> tuple[str, bytes]:
    """Return (compression, decoded JSON bytes) from shellball text."""
    match = re.search(r'^PN_COMPRESSION="(\w+)"$', text, re.MULTILINE)
    if not match:
        raise ValueError("not a jsonball: PN_COMPRESSION not found")
    codec = match.group(1)
    if codec not in CODECS:
        raise ValueError(f"unknown compression: {codec}")
    _, _, payload = text.partition(f"\n{PAYLOAD_MARKER}\n")
    if not payload:
        raise ValueError("not a jsonball: payload marker not found")
    blob = base64.b64decode(payload)
    if codec == "xz":
        return codec, lzma.decompress(blob)
    if codec == "bzip2":
        return codec, bz2.decompress(blob)
    if codec == "gzip":
        return codec, gzip.decompress(blob)
    return codec, blob


def load(path: Path):
    """Load JSON from a shellball (importable convenience API)."""
    return json.loads(parse_ball(path.read_text())[1])


def self_test(ball: Path, expected: bytes) -> None:
    """Run the composed shellball and check its inputs and outputs."""

    def run(*args: str) -> bytes:
        return subprocess.run(
            ["sh", str(ball), *args], check=True, capture_output=True
        ).stdout

    assert run("cat") == expected, "cat round-trip mismatch"
    assert run("verify").startswith(b"OK:"), "verify failed"
    assert b"base64" in run("tools"), "tools does not name its pipeline"
    assert b"sha256:" in run("info"), "info is missing metadata"

    with tempfile.TemporaryDirectory() as tmp:
        extracted = Path(run("extract", tmp).decode().strip())
        assert extracted.read_bytes() == expected, "extract round-trip mismatch"

    # tools tells us what the decode pipeline needs; test the claim
    tools = run("tools").decode()
    required = tools.splitlines()[1].split(":", 1)[1].split()
    for tool in required:
        assert shutil.which(tool), f"required tool not available: {tool}"

    if shutil.which("jq"):
        assert json.loads(run("query", ".")) == json.loads(expected), (
            "query round-trip mismatch"
        )

    # python-side reader agrees with the shell side
    _, data = parse_ball(ball.read_text())
    assert data == expected, "python parse_ball mismatch"


def cmd_pack(args) -> int:
    data = args.input.read_bytes()
    json.loads(data)  # must be valid JSON
    name = args.input.name
    output = args.output or args.input.with_name(name + ".sh")

    text = compose(data, name, args.min_compress_size)

    with tempfile.NamedTemporaryFile(
        "w", dir=str(output.parent), suffix=".tmp", delete=False
    ) as f:
        f.write(text)
        tmp = Path(f.name)
    try:
        self_test(tmp, data)
    except AssertionError as e:
        tmp.unlink()
        print(f"error: self-test failed: {e}", file=sys.stderr)
        return 1
    tmp.replace(output)
    os.chmod(output, 0o755)

    codec = re.search(r'^PN_COMPRESSION="(\w+)"$', text, re.MULTILINE).group(1)
    print(
        f"{output}: {len(data)} bytes of JSON -> {output.stat().st_size} bytes "
        f"({codec}), self-test passed"
    )
    return 0


def cmd_unpack(args) -> int:
    _, data = parse_ball(args.ball.read_text())
    if args.output:
        args.output.write_bytes(data)
    else:
        sys.stdout.buffer.write(data)
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    pack = sub.add_parser("pack", help="pack a JSON file into a shellball")
    pack.add_argument("input", type=Path)
    pack.add_argument("-o", "--output", type=Path, default=None)
    pack.add_argument(
        "--min-compress-size",
        type=int,
        default=DEFAULT_MIN_COMPRESS_SIZE,
        help="payloads smaller than this stay uncompressed (default 1024)",
    )
    pack.set_defaults(func=cmd_pack)

    unpack = sub.add_parser("unpack", help="decode a shellball from Python")
    unpack.add_argument("ball", type=Path)
    unpack.add_argument("-o", "--output", type=Path, default=None)
    unpack.set_defaults(func=cmd_unpack)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
