#!/bin/sh
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
#
# asan-summary.json -- JSON shellball generated by scripts/ci/jsonball.py; do not edit.
# Regenerate with: python3 scripts/ci/jsonball.py pack <input.json>
#
# The JSON payload is embedded below the __JSONBALL_PAYLOAD__ marker as base64 text
# (compression: gzip). Run with no arguments or "help" for usage.

set -eu

PN_NAME="asan-summary.json"
PN_COMPRESSION="gzip"
PN_DECODE_CMD="base64 -d | gzip -dc"
PN_TOOLS="sed base64 gzip"
PN_SHA256="e1f7419ec984ff3ace6226b54eae55ea9df2cb8674fd14aad461f1cf242904f2"
PN_SIZE=10978
PN_ENCODED_SIZE=895
PN_MIN_COMPRESS_SIZE=1024
PN_COMMIT="06465a9cc4f7ec3555703615e3e0b8138239d23e"
PN_CREATED_AT="2026-08-02T17:38:40Z"

payload() {
	sed -e '1,/^__JSONBALL_PAYLOAD__$/d' "$0"
}

decode() {
	payload | base64 -d | gzip -dc
}

usage() {
	cat <<EOF
usage: sh $0 <command> [args]

$PN_NAME: self-extracting JSON archive ($PN_SIZE bytes of JSON,
$PN_ENCODED_SIZE bytes encoded, compression: $PN_COMPRESSION).

commands:
  cat            decode the JSON to stdout
  extract [DIR]  decode to DIR (default: a new temporary directory);
                 prints the path of the extracted file
  query EXPR     run "jq EXPR" against the decoded JSON (requires jq)
  commit         print the commit the data was collected from
  created        print the collection timestamp
  sha256         print the expected sha256 of the decoded JSON
  tools          print the decode pipeline and the tools it requires
  info           print all embedded metadata
  verify         decode and check against the embedded sha256
  help           show this help
EOF
}

cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
cat)
	decode
	;;
extract)
	dir="${1:-$(mktemp -d)}"
	mkdir -p "$dir"
	decode > "$dir/$PN_NAME"
	echo "$dir/$PN_NAME"
	;;
query)
	decode | jq "$@"
	;;
commit)
	echo "$PN_COMMIT"
	;;
created)
	echo "$PN_CREATED_AT"
	;;
sha256)
	echo "$PN_SHA256"
	;;
tools)
	echo "decode pipeline: sed -e '1,/^__JSONBALL_PAYLOAD__$/d' $0 | $PN_DECODE_CMD"
	echo "required tools: $PN_TOOLS"
	;;
info)
	echo "name: $PN_NAME"
	echo "compression: $PN_COMPRESSION"
	echo "decode: $PN_DECODE_CMD"
	echo "tools: $PN_TOOLS"
	echo "sha256: $PN_SHA256"
	echo "size: $PN_SIZE"
	echo "encoded-size: $PN_ENCODED_SIZE"
	echo "min-compress-size: $PN_MIN_COMPRESS_SIZE"
	echo "commit: $PN_COMMIT"
	echo "created-at: $PN_CREATED_AT"
	;;
verify)
	actual=$(decode | sha256sum | cut -d' ' -f1)
	if [ "$actual" = "$PN_SHA256" ]; then
		echo "OK: $PN_NAME sha256 $actual"
	else
		echo "FAIL: $PN_NAME sha256 $actual != $PN_SHA256" >&2
		exit 1
	fi
	;;
help | *)
	usage
	;;
esac
exit 0
__JSONBALL_PAYLOAD__
H4sIAAAAAAACA+2azY6bMBCA73mKiPOuSiBks3mOnlpVI8cMYK2xkceQrFZ59xryU1LtYd2IHpBP
CTO2M/n8MzMePhbLZVQa3TYU7ZYf7sk9M3pXvDJa6ZZA6JvCqYijYkZoGgmHHkzdSZyM61ZZ+kvq
5A0jwtzJs5H89DTuWjAhMYeiVdwKrfpBfv76rEUjmS20qT9pcae6t0AxKzoEEvW389dopL8fhSyz
bT/E1eyb8rQYf17sj/bMGIGGpmK2niEzDpKpEqhtGm0smMDOi53YAx5tgOYBTWr+BoQSB8sDuq+j
y7ETHCd0CnOEhh0qW+RTIVvNEFmRQ13W4VTzQebMgv5kE6oM3Dy50TtZrEOk+3VsNRKxEqFvPeGK
myW61gpojOYO4VTc0hlyU2gP2oTzzZOaVtAnVmwvcSpuyQy5NZrEEQwyaUXd/0SpmAyJvTfBs2uF
nLkVyAgDwAcBhgsSH4TmMMTEYd96MCOsWVNpg4GaD7XgIP4R2ZT3l9kssanS5awTZxCzJNcINa0/
mCM1W7koOAdyWQTLBQdC06EJmasvQYIpA+BsxtxCgcsPm0tYp6tBb2ZI7EgCWN4xxZ1115w/FGwe
BAiX/RtA+oEM/B7j938C5PVc6Vm36OpQmfDFdr6mk7osQ4XCm16I9PzQLS7/IXKHXOcYOb/75wVO
ruta9ByjeLPeZOyV83XxgjzNsuwlTjerDFOM99tVuk3S1zxJMXoa9wSqtBn3v6ndJFnHgQ3KJE42
z/H2OU6+r1526Xa3jn9cWzqz+sJ638wehNsZBoZJuybiFTPDbDfI7TA7qpXyXmmwL1udHdVF05f/
CqkPYFoFrZH98NENBfEKawYuN6Xza12rxWnxG1xA2eLiKgAA
