#!/bin/sh
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
#
# static-analysis.json -- JSON shellball generated by scripts/ci/jsonball.py; do not edit.
# Regenerate with: python3 scripts/ci/jsonball.py pack <input.json>
#
# The JSON payload is embedded below the __JSONBALL_PAYLOAD__ marker as base64 text
# (compression: gzip). Run with no arguments or "help" for usage.

set -eu

PN_NAME="static-analysis.json"
PN_COMPRESSION="gzip"
PN_DECODE_CMD="base64 -d | gzip -dc"
PN_TOOLS="sed base64 gzip"
PN_SHA256="cda434d5fa5ed34ce8d8d7d84108d5da9f0836ad0ae002c5304443ab58573458"
PN_SIZE=10948
PN_ENCODED_SIZE=2597
PN_MIN_COMPRESS_SIZE=1024
PN_COMMIT="06465a9cc4f7ec3555703615e3e0b8138239d23e"
PN_CREATED_AT="2026-08-02T17:27:45Z"

payload() {
	sed -e '1,/^__JSONBALL_PAYLOAD__$/d' "$0"
}

decode() {
	payload | base64 -d | gzip -dc
}

usage() {
	cat <<EOF
usage: sh $0 <command> [args]

$PN_NAME: self-extracting JSON archive ($PN_SIZE bytes of JSON,
$PN_ENCODED_SIZE bytes encoded, compression: $PN_COMPRESSION).

commands:
  cat            decode the JSON to stdout
  extract [DIR]  decode to DIR (default: a new temporary directory);
                 prints the path of the extracted file
  query EXPR     run "jq EXPR" against the decoded JSON (requires jq)
  commit         print the commit the data was collected from
  created        print the collection timestamp
  sha256         print the expected sha256 of the decoded JSON
  tools          print the decode pipeline and the tools it requires
  info           print all embedded metadata
  verify         decode and check against the embedded sha256
  help           show this help
EOF
}

cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
cat)
	decode
	;;
extract)
	dir="${1:-$(mktemp -d)}"
	mkdir -p "$dir"
	decode > "$dir/$PN_NAME"
	echo "$dir/$PN_NAME"
	;;
query)
	decode | jq "$@"
	;;
commit)
	echo "$PN_COMMIT"
	;;
created)
	echo "$PN_CREATED_AT"
	;;
sha256)
	echo "$PN_SHA256"
	;;
tools)
	echo "decode pipeline: sed -e '1,/^__JSONBALL_PAYLOAD__$/d' $0 | $PN_DECODE_CMD"
	echo "required tools: $PN_TOOLS"
	;;
info)
	echo "name: $PN_NAME"
	echo "compression: $PN_COMPRESSION"
	echo "decode: $PN_DECODE_CMD"
	echo "tools: $PN_TOOLS"
	echo "sha256: $PN_SHA256"
	echo "size: $PN_SIZE"
	echo "encoded-size: $PN_ENCODED_SIZE"
	echo "min-compress-size: $PN_MIN_COMPRESS_SIZE"
	echo "commit: $PN_COMMIT"
	echo "created-at: $PN_CREATED_AT"
	;;
verify)
	actual=$(decode | sha256sum | cut -d' ' -f1)
	if [ "$actual" = "$PN_SHA256" ]; then
		echo "OK: $PN_NAME sha256 $actual"
	else
		echo "FAIL: $PN_NAME sha256 $actual != $PN_SHA256" >&2
		exit 1
	fi
	;;
help | *)
	usage
	;;
esac
exit 0
__JSONBALL_PAYLOAD__
H4sIAAAAAAACA6Waz2/cKBTH7/0ropy6Uhpn8rPtbbXSSivtYQ/by64qxODnGTYYKOBJJlX/930P
eybj6dhAe0gGw+cLBj8eD+yvb87OzrnmavsCNWukAn/+8exfzMV8JZeVNV4+V4IprlfMd9YaF5ir
uBdBtsDcpTi/SNIl7KotgJURXBXwX3z8zWId13Um6oMD54zLx4N5nITlksFzqBrd8iDW89AKAujg
jN0mOWNDDsOU0ask6Ltlsj4frEjdFw6F4B5Ea5Nc3aWZpjU6CencFrWCRG0vYNdbx6ZHFzb4eJp6
93sKQaU02uOU2mqxdkabzjNpKi4NE1wLUKWqaIuloobySkUOeF2uCZ3TpSrfeQu6uLEnJwOUiBSK
lPRYOKdacuckuH1ijhXopB6ZBwWCMoZrzbXxCsCWSG1Y04gzYXTNQ4iGF5mfqsTnVGI7crNDZdSs
7WJazj6SGjZSAI0rwh7y0KY2FnQmiyuWNnlsfq02OYMOWKNUJpmaLQdo/7gy4aSRv7L5t1ByB8kb
aGrW4sJeTfjwE9h1DtcIHVQW6AEeTRYZQKlM0nW4lOR1XNENzIJoyCxOKL0aXSRFfusDtNjFTBID
kNHVrIy8Y5VcGlpu7S58rFq8moWhpa5V8T+fnzwDyzAWW0GvSODGbZl1JgzOrh3S8yrv+QqY5d7T
6LdfWNJbndCgUyR3WqjSJshmWyhKebITEgcC5Ka0Tz6x5J6U/Mgw0OJS/9g9RukP3GinldTz5tTh
3oKsSaB6fJUvSy7yGsKTcXHecyHAhkx4Kee7fIDiUq8Tk+CAbhzgKlE7qRuTKVlxyXaboFwJ2klh
IxDWxgfNW8hXEF3WhgVwZW14dEvlCpP9pGXD8FnjfsMUtIKivu8oLJMEUyTCNKMnWcLrYHghb0t4
G4zO5CnYh1wYkzXu/HTuk0OPtilAG2faArz1q0w65R6P0LKKg8mGCw3fr7tQm6fcp0OV89By91gg
gFAEWy7nLd1oRsc8fKlgv9XSs8ZrnTQYQG+ZF2uoOxUbo+ScCOvtD768XGmuMCNgalbxFENKSqTi
KA8Yw62Ng4PkLL/mDuoK9AZ3lW07P/cGOGbiUBmVAw8DuRuqDAmOBmwyOBrEDVcsmBhJeAsiQ/VC
406xTpplQ1Rqlv/hGky5s3N89zz73wxyd1qVI9ArDPx3kQlGBY2fj9SOFPiAC2jcYFATBYoutb55
K/VgxZRM2vFwtiPpcDueLPDAU5uZYV9E6JJ7OL4ukNJR71EOGvDm52qYfV67o53htGY3bbLPa46m
2aFH2tWV9Ew951kcPDpkyoYfYZvNtl2YD1FG9HDzpTzrz8cCx3UlEeEk5B5NsFge+xgfRo6U3MCo
4VXHXZ3b8KE6thurCFs7r0Yrc/71VBBXjBKcrrN5n81nna0ObPxhAvsdIBuvQUEBTq8HNrg36nSJ
JLOzPZ8/OF1yZJ49bubGjvn7rGQFaAu89bQwYXYa772cMqtVDH+2HpMp0SnbRYcjOudAi5O+xK9B
qal1rC/sA5OYnoaOVqr+PRA6MKdBob0C14cnnUfF6BM33E0VSy3DVBkG5uzLZOHYJY4Lj9z2UeFR
6DAuPfadR6VoVqYLc8WTXQ2HdjQU0UiD4j5Iig0PkidJ/BNVH3NigN45AUNnKselh0LNxDhMiUJN
McXRWWGWZnyAl5RQCV/iriJXg4+sroSui/g2PBfxONOgSED/ygQT9nGKp3hn+CqhSFOu2H90MK1q
cRK3ZFC9LCp2P9mqwVYoePsBjS/VjN9QZGnwP0598rneFHesXyEoPAql0tBaetdQoopTCP2jDKWq
+M1IgcjFBey7w9Bs3eidT0L1+k62TNJ/ZDOtsVKYmHjZNJ6+djhtgcbTS/apIrHE0FWHhlmKn1dQ
T4KTHcDC9ksHHUyVYqDATi8xAzCxeI1K6UDPbacYGoJ+HKY9/Qg7eis5idXxkCgDPPk2cJL2OQxO
uhxstFWexL5/ETqFSiNyhoYMjk3O8DE66bZG2Pgt/RTlQBhXszlzPICfTjK481a+WgO3bNJx9AzZ
LaW+Q3y3RLums8dI9wePfvc7hfeBaWtwvw7x5XyLAbUHRy/p8zR9VLbTVJ096SRG0qMweRJhT1LV
gp9Y/wc2gA++kwGqF0pW3ok+hQLkP5PovJG6xkkQP1Hsc3A3sgFNX0lh3te+4vg5o5d+n4N5dBAl
VwzDbsl1oKLF7WJxsS8OHWahHcM+CzcVjjOMmnHQ3etHkbGMNiH6sj/mlYrOIz9p+fzrX3+cX7xC
HnAjQmW/K8PDn8bY30ynA7jzgfm8b+vlZmg9Zny7OOjHC27ucO/ocdODzPmnJVbRnQn6ovBsyD9b
vL9cXN6cvV10sXTxy26IKXiRgXRX97f3d/yDELfNA4ibu7u7h6ub+8Ud3MDV8v3i5v31zYf6+gbG
StwFYR8P9PviuF+mcwYqvL66vn939f7d1fXfi4eP1w8fb+/+2ZEBI3di+jv2gut3yw5t4ezt0L3+
cn/LdNreKPPE0KewzkUtDVgclHPaxbT8YEAWb769+R8egqj2xCoAAA==
