#!/bin/sh
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
#
# twister-summary.json -- JSON shellball generated by scripts/ci/jsonball.py; do not edit.
# Regenerate with: python3 scripts/ci/jsonball.py pack <input.json>
#
# The JSON payload is embedded below the __JSONBALL_PAYLOAD__ marker as base64 text
# (compression: bzip2). Run with no arguments or "help" for usage.

set -eu

PN_NAME="twister-summary.json"
PN_COMPRESSION="bzip2"
PN_DECODE_CMD="base64 -d | bzip2 -dc"
PN_TOOLS="sed base64 bzip2"
PN_SHA256="3d78af01cb73d584f178a911a3fff21f1cd265e3d87b5c40325b878493bcf31b"
PN_SIZE=42904
PN_ENCODED_SIZE=1775
PN_MIN_COMPRESS_SIZE=1024
PN_COMMIT="472ad132ab169eaa9487c30ed9f0455c007a8060"
PN_CREATED_AT="2026-08-02T06:53:58Z"

payload() {
	sed -e '1,/^__JSONBALL_PAYLOAD__$/d' "$0"
}

decode() {
	payload | base64 -d | bzip2 -dc
}

usage() {
	cat <<EOF
usage: sh $0 <command> [args]

$PN_NAME: self-extracting JSON archive ($PN_SIZE bytes of JSON,
$PN_ENCODED_SIZE bytes encoded, compression: $PN_COMPRESSION).

commands:
  cat            decode the JSON to stdout
  extract [DIR]  decode to DIR (default: a new temporary directory);
                 prints the path of the extracted file
  query EXPR     run "jq EXPR" against the decoded JSON (requires jq)
  commit         print the commit the data was collected from
  created        print the collection timestamp
  sha256         print the expected sha256 of the decoded JSON
  tools          print the decode pipeline and the tools it requires
  info           print all embedded metadata
  verify         decode and check against the embedded sha256
  help           show this help
EOF
}

cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
cat)
	decode
	;;
extract)
	dir="${1:-$(mktemp -d)}"
	mkdir -p "$dir"
	decode > "$dir/$PN_NAME"
	echo "$dir/$PN_NAME"
	;;
query)
	decode | jq "$@"
	;;
commit)
	echo "$PN_COMMIT"
	;;
created)
	echo "$PN_CREATED_AT"
	;;
sha256)
	echo "$PN_SHA256"
	;;
tools)
	echo "decode pipeline: sed -e '1,/^__JSONBALL_PAYLOAD__$/d' $0 | $PN_DECODE_CMD"
	echo "required tools: $PN_TOOLS"
	;;
info)
	echo "name: $PN_NAME"
	echo "compression: $PN_COMPRESSION"
	echo "decode: $PN_DECODE_CMD"
	echo "tools: $PN_TOOLS"
	echo "sha256: $PN_SHA256"
	echo "size: $PN_SIZE"
	echo "encoded-size: $PN_ENCODED_SIZE"
	echo "min-compress-size: $PN_MIN_COMPRESS_SIZE"
	echo "commit: $PN_COMMIT"
	echo "created-at: $PN_CREATED_AT"
	;;
verify)
	actual=$(decode | sha256sum | cut -d' ' -f1)
	if [ "$actual" = "$PN_SHA256" ]; then
		echo "OK: $PN_NAME sha256 $actual"
	else
		echo "FAIL: $PN_NAME sha256 $actual != $PN_SHA256" >&2
		exit 1
	fi
	;;
help | *)
	usage
	;;
esac
exit 0
__JSONBALL_PAYLOAD__
QlpoOTFBWSZTWaZDdrkAQk/bgFVQUAf/8AQav+//6mAHnz7421F75vJURCSgAAAw0NNADQAGgABk
NA0CRqMEBhNAGgBppoBo9SiAAABoDQANACT1UpQ1NMAExNBhGRkaYEESKI0mmmk09ANNCGCZqGjI
FKiCAjEJoU9QbUNAHqPUejeJUvxyMYI/ShmhihihlRc4hmIZpRZSHjv4y9F6liaSDGwjQxpIscAG
m1hcSFxozkp1eja1fgqzSQyxTMYqYYE3NaxtWlcaKgowQbRoqxUa0bFUVMTGCWMSZw5csbc6VInd
UqXzKiCBCCKqQ70ED0dWqn7xu6LhcDJMyEw24uNzo4nRyg6NqgQau4WlxKhIkgSa5UuqJfRhu+cE
ddRYMjKxiNJGXWOOKNwRJoxyRxYrnOcnDnOBKc7HREURYgxTpy43FzpzNQCo3CaH3ff2gCBhwou+
Ko2oICh3b2xMyozBDM0OYw5T9PYQqyvMiAD+7IZAhWVWCRCHHd0IQiWIUBbCFBAeYGTyJCcHTiGE
CGBhCdxxxApYaIQhmFFxBA2m4EInaggQqcfdgggW3hIMziq1pGcKTGWNBDSIaVWsQ1NdUKz+VDTN
tgxbRDJm0waQ6w2kBkJ00BIqK+gggWInZFUGzy8fnfr+ndXP4KIbhMojICO7zgomP1oNUThv2fLl
/X7d/9c/htn5Qfk9ci8qR75zN6mICeC64qrs47x9vFRDLPkAH1VRefRw1LxwwkfZQfL3xz99nP8I
n/KRhE76a0jiz1751x060j9so4deG23f38VBXw0179fREPsi/jhSYiG9I81AHuaeCxT4FAO09cHb
Dz2/aV2fOWnfn35OWKCBlXFPCVhrquHEQTWIJq9uDDQqJlx6Mbvhx0mHFZWo6dSqh3igHXfJn6dY
fAz8WYcMTQbPJSHKq8n88W8wxypGdHx2/DWh86jzRD8uuVPldOSId7iUnWUZiHr6e3TPTNDOgM5d
ReMD6/DZvOnBZy4UPldc6bam+4Pxl0KjCQ7N+JEzEQOWyioogViZ5msOaExovmFE5Orn03VXWyrh
EZEcKoCV1QvHMKJdHhpR6MMyLGChjkyUvzzpEObttqfsz+lSp13oY543zw668K1+nC57+/fbmoPW
a99qQ1x7w3WIIHBmDiJsz3s6MTVgnBxmjlq9I4aLvAkHvBm78vTkDb0cPp5ZnyvFIZUmlV0XF6PP
a61XRT2acHWh5ImCJ/Dg47FJueG7Fjyg5dUQ9O7HJj54pDZ8AcPZTnqeurysLHrcJRyxyUmTFVjD
bBy46ZquzcWaR5ohr141KmuzWkcc/uzvOn34kfFSclJytc/44muHliq6WdrPTGnLSIbC87yvcxjw
DzlGItm3G30x6/T3eyIZ0uKg3oZNNIhvxxz912hDp8FPr6a378FbsCG+MCGeufT32vXWyzzpHrtQ
ayRhExKN92PZ0eFrOHjOdvXxwobETV1wiHkct/jpw6XPFcHsiYEOfnr59Yh2RDn9PG/tnGO2uPo4
daG7fziGfdzKORp0zv06kdiJ3Uawh314LOWPcdNO+uWFJvnOnmYWmjnOSIZ0KHzOnDV8cb4Mcduj
xhqpjz2om2rO/WUNPjrnSZUHnoiHluwxw7a3ebcmhSZvfnpKPXNziGusQ29O1Spr5PEQ448+cQzx
XDmp0Im/Z2KTh16bZwiZ0588b7SjdQdlNLOwxOxy8p+aUn//vQ+9D76YQyov7RDZ+ou5IpwoSFMh
u1yA
