#!/bin/sh
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
#
# twister-summary.json -- JSON shellball generated by scripts/ci/jsonball.py; do not edit.
# Regenerate with: python3 scripts/ci/jsonball.py pack <input.json>
#
# The JSON payload is embedded below the __JSONBALL_PAYLOAD__ marker as base64 text
# (compression: bzip2). Run with no arguments or "help" for usage.

set -eu

PN_NAME="twister-summary.json"
PN_COMPRESSION="bzip2"
PN_DECODE_CMD="base64 -d | bzip2 -dc"
PN_TOOLS="sed base64 bzip2"
PN_SHA256="ff2ec7da6800cb1e81ae582fa6bc0e83bea3da2d0ee296205c575389cfea6f8e"
PN_SIZE=33577
PN_ENCODED_SIZE=1584
PN_MIN_COMPRESS_SIZE=1024
PN_COMMIT="d478cd7dfe30e5b80ef34d2ed2bf3b84c1f48fb2"
PN_CREATED_AT="2026-07-26T21:06:55Z"

payload() {
	sed -e '1,/^__JSONBALL_PAYLOAD__$/d' "$0"
}

decode() {
	payload | base64 -d | bzip2 -dc
}

usage() {
	cat <<EOF
usage: sh $0 <command> [args]

$PN_NAME: self-extracting JSON archive ($PN_SIZE bytes of JSON,
$PN_ENCODED_SIZE bytes encoded, compression: $PN_COMPRESSION).

commands:
  cat            decode the JSON to stdout
  extract [DIR]  decode to DIR (default: a new temporary directory);
                 prints the path of the extracted file
  query EXPR     run "jq EXPR" against the decoded JSON (requires jq)
  commit         print the commit the data was collected from
  created        print the collection timestamp
  sha256         print the expected sha256 of the decoded JSON
  tools          print the decode pipeline and the tools it requires
  info           print all embedded metadata
  verify         decode and check against the embedded sha256
  help           show this help
EOF
}

cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
cat)
	decode
	;;
extract)
	dir="${1:-$(mktemp -d)}"
	mkdir -p "$dir"
	decode > "$dir/$PN_NAME"
	echo "$dir/$PN_NAME"
	;;
query)
	decode | jq "$@"
	;;
commit)
	echo "$PN_COMMIT"
	;;
created)
	echo "$PN_CREATED_AT"
	;;
sha256)
	echo "$PN_SHA256"
	;;
tools)
	echo "decode pipeline: sed -e '1,/^__JSONBALL_PAYLOAD__$/d' $0 | $PN_DECODE_CMD"
	echo "required tools: $PN_TOOLS"
	;;
info)
	echo "name: $PN_NAME"
	echo "compression: $PN_COMPRESSION"
	echo "decode: $PN_DECODE_CMD"
	echo "tools: $PN_TOOLS"
	echo "sha256: $PN_SHA256"
	echo "size: $PN_SIZE"
	echo "encoded-size: $PN_ENCODED_SIZE"
	echo "min-compress-size: $PN_MIN_COMPRESS_SIZE"
	echo "commit: $PN_COMMIT"
	echo "created-at: $PN_CREATED_AT"
	;;
verify)
	actual=$(decode | sha256sum | cut -d' ' -f1)
	if [ "$actual" = "$PN_SHA256" ]; then
		echo "OK: $PN_NAME sha256 $actual"
	else
		echo "FAIL: $PN_NAME sha256 $actual != $PN_SHA256" >&2
		exit 1
	fi
	;;
help | *)
	usage
	;;
esac
exit 0
__JSONBALL_PAYLOAD__
QlpoOTFBWSZTWe2AuJwAM+3bgFVQUAf/8AQav+//6mAGfn3zfY3cxlPkBQAAMYaGmgBoADQAAyGg
SVNPVMCbUADQGmgGgACRqlIAaAANAaABoAZ6pVTI2gmTAAIyYACMCapJEjINMgNBo0ANGnpAEUQQ
JpkmjJM1Q2TUMI0D0nFCJf3jZlVf6GoZDIaorkkmpJqBWpJyua514xi0yZRzgkgkhKgE0CizBDRh
Y80UMIgYiFpYFCVCLZqSyypZiQlkKilhYWosRLC2QRSWSTWXHx5v5JKVV4ihLoawkyykoFOwhCec
Nqwy1yrZbMFHC9zi4shgohCBiZCFlyPsyiEhy7XJz/OiS2aIEJCUskRdFDIxQzJmLmZIXEKgmM0Z
EmQYCgGZrEzLWMzLNYzvdrr7ZJu8IvziS2REaEW+tCjEG95C1fvhWv+EGNFX7GBWIRpimvcjUpYj
UoiLEVmFwooWUURYtqKfNhgxS5CEJm6iSWHWQkzls2zaSY22zKl1IbZUrNWbSTaSbSbpJurduqi1
1Q20bpJje2xo9jpsLMs+WjMoL7Uk2JST9+34/njv6T3/FFeygZQBECnb6QAhb8wBqiuHsUxy+d6/
XoI3PKVds0V5+H2jT4mCr8gqc/T2fFDN8XmIXR3bdrm5+IaQ7KqfDhp32PdFf6QAhFeVaoAa08dZ
8SvU2RXsoBcsdRAFPHLvN+YIj9xEfURGqACYAF6HywiX0AFrOjBeyayDR+msrcIQmoiK2hfA6dkJ
J6ElN0hkQIH0Susace4tUFVsAA+IAPdwD3Y9sksewiNxHL5Q2SCLorNDwt7lRXqIGgIjnAvVzxBE
bgCGagHARHXXt6cv07uMis0UfaTcR849Ll/Y2waSYCvkbzagYXUfeTgKjCiPMvgIrIojvHCx2KVg
FHAyi3tk+cEXkr5gIdc/PWKSTFIaTMR4wqa/rWxW+ACFJNAfOlkADIhQTrNBEcTfO9ntP4RUDhgK
wTxQW5WjTaYzLdhlABYUNgp4RiELPG6SlxUwIR0zdu08qBhuX6zTFPSZoRAdQXHvwUad5pcPg+Qi
MgIUEchwNiuYjkL0pczFdEVgRX1wONgBC4bFyGNVHLgCI79CMo6wIjbvUcOYudXnU1YGLqAYxiAh
LAjEFYC84iPEuASiuoIjXTFFQK2KorjPpNwz/vFV6AIZAIZMfTEpGsCMVc9MZERsr1dToEclHioB
CBYtFe3Q5giM+DgADcVkKUERuZdHiCI+Avt3UA9YELECI8xEdI7vCrzqSTmivOwA1RRhFYUAsX79
DdKphvM27uWArYRWpwgER1bdZvo5QFzmisCA5ceOgiOwIjnv5ee00nh4WjDgKycREY6mYq3KQ4cF
XYRXdAOAIjvXZgnoO1KRACETxCGaZGIIjNBEfg54VOsBfG2Tyiosa2FW1Sb6qI06VmgSADyoCI2N
YjDbdKZFwBCXrnRQDnLmIjWoiNu7ZFQK6nIRHGOOYiOLhmLoIrbY2AEMeFYhFdKZ5xeygFwAdhaM
2GE2y1fmKVfzhDhDhtiNUV1yTff8XckU4UJDtgLicA==
