#!/bin/sh
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
#
# twister-summary.json -- JSON shellball generated by scripts/ci/jsonball.py; do not edit.
# Regenerate with: python3 scripts/ci/jsonball.py pack <input.json>
#
# The JSON payload is embedded below the __JSONBALL_PAYLOAD__ marker as base64 text
# (compression: bzip2). Run with no arguments or "help" for usage.

set -eu

PN_NAME="twister-summary.json"
PN_COMPRESSION="bzip2"
PN_DECODE_CMD="base64 -d | bzip2 -dc"
PN_TOOLS="sed base64 bzip2"
PN_SHA256="df88c7978d82b224fbd7541c746e84733127911df04a3bea0998344b33b3c293"
PN_SIZE=41031
PN_ENCODED_SIZE=1746
PN_MIN_COMPRESS_SIZE=1024
PN_COMMIT="9152ba217239d866209ccfb05a85dca9e3f382bb"
PN_CREATED_AT="2026-08-02T14:48:04Z"

payload() {
	sed -e '1,/^__JSONBALL_PAYLOAD__$/d' "$0"
}

decode() {
	payload | base64 -d | bzip2 -dc
}

usage() {
	cat <<EOF
usage: sh $0 <command> [args]

$PN_NAME: self-extracting JSON archive ($PN_SIZE bytes of JSON,
$PN_ENCODED_SIZE bytes encoded, compression: $PN_COMPRESSION).

commands:
  cat            decode the JSON to stdout
  extract [DIR]  decode to DIR (default: a new temporary directory);
                 prints the path of the extracted file
  query EXPR     run "jq EXPR" against the decoded JSON (requires jq)
  commit         print the commit the data was collected from
  created        print the collection timestamp
  sha256         print the expected sha256 of the decoded JSON
  tools          print the decode pipeline and the tools it requires
  info           print all embedded metadata
  verify         decode and check against the embedded sha256
  help           show this help
EOF
}

cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
cat)
	decode
	;;
extract)
	dir="${1:-$(mktemp -d)}"
	mkdir -p "$dir"
	decode > "$dir/$PN_NAME"
	echo "$dir/$PN_NAME"
	;;
query)
	decode | jq "$@"
	;;
commit)
	echo "$PN_COMMIT"
	;;
created)
	echo "$PN_CREATED_AT"
	;;
sha256)
	echo "$PN_SHA256"
	;;
tools)
	echo "decode pipeline: sed -e '1,/^__JSONBALL_PAYLOAD__$/d' $0 | $PN_DECODE_CMD"
	echo "required tools: $PN_TOOLS"
	;;
info)
	echo "name: $PN_NAME"
	echo "compression: $PN_COMPRESSION"
	echo "decode: $PN_DECODE_CMD"
	echo "tools: $PN_TOOLS"
	echo "sha256: $PN_SHA256"
	echo "size: $PN_SIZE"
	echo "encoded-size: $PN_ENCODED_SIZE"
	echo "min-compress-size: $PN_MIN_COMPRESS_SIZE"
	echo "commit: $PN_COMMIT"
	echo "created-at: $PN_CREATED_AT"
	;;
verify)
	actual=$(decode | sha256sum | cut -d' ' -f1)
	if [ "$actual" = "$PN_SHA256" ]; then
		echo "OK: $PN_NAME sha256 $actual"
	else
		echo "FAIL: $PN_NAME sha256 $actual != $PN_SHA256" >&2
		exit 1
	fi
	;;
help | *)
	usage
	;;
esac
exit 0
__JSONBALL_PAYLOAD__
QlpoOTFBWSZTWfB79/cAP3JbgFVQUAf/8AQav+//6mAHnfQoFKqAASAAAAYaGmgBoADQAAyGgw0N
NADQAGgABkNBhoaaAGgANAADIaBCUlCeqaPU9QDRoGQABoaGGhpoAaAA0AAMhoCpIQE0E0TJqJ6e
lNPSek2p6R6jyd6Kgj/3YKBD2qBlAlAlAysjdAWQFkgS0gOs7HhO8njEkzDDwZyzmCOlbcSXDDJw
m8PSqh5qIWKCkqhpKoIokiCgiMgASmIKaaKEpKpoKaaKCmhKBpRopCqILU22rLeSIkkOyCInqWpA
CIURSPUIAes/R8Y8bTcMm5rGC25ciKvf25BosbRyOUdUTq2cUdTyHRE1yDSlzb0+v4Ps9vZVOxUk
UVQUxAVVJQUEV2a1thIk1S6YgtqNRLPmK5HJ5Ia2dM0vLkcmiktZ20XnfY+z96gGfSI+tSSJeIC/
8Vi+d6tJj+fsxWmXffD3avDrXhzigddErc/Z3ubBEVf1zHNN38xc8ornCjawWiNinO2DmDctYsss
xdepSlS5eQHwexCo+KAI15eroQA48OgDSr0ihoASxXgF4BeSTCAwYwiRLf3kF7PdBPcIAYM8hyH1
B9ZA0X4YCkRJ/BAXIklnw+f49unX428/jEh8IGtQqpJPy/egjL2hDCQaf4a/PfjS+PcJ9PovdJPr
vEh5dr/79L1/l56kLIQ8sv5+cSHHx0STKIiePLy4yicRIXc0IYvtTXx8PukH/IQpIMs6hDbXWtUk
NvzfvUIevuVnnngkiJ5758q6kB/MSH60RKQHOEOEIfZ03uH3Qh7Ppg9q9f3/Wrf2/GvL66fXWa5I
DW3Sv2q2OtrcZJB1SDn9d8bQRr22yvfjLkx0utzevOCHg/RCHy48ep90r9uOdRq8v2IGsknR+tTO
KrWJC13pl92JB1khzkA+PFg9Jy2IDrNQRxIhZAbd+nl7Ofu6WkFr4Be7Q70SXYjp8ueiYs0kHrPP
rfGeRtoD72c0EVIDuz1JBZIDrxa1EDGbX321we+lZ2X94BPk8vR73NnklctAfLBiWl8d19Edd/gA
JzHnR9HO4RClRoE7EijYQBq64wetvxCJG+cgras7ab40kx6aTfPz65boQ7xj5ZEDXK3pT4XIDGZ0
V5aX8fXJzxG/Zt5W5JfbK+FUnaBadtu+wMu7T8udo9Z4ECwReSTkmq/fpVnEknIPJfRxIOaQUSD9
NG2QIzPBmqVzgbcEB37K2V60QMnuBp5Bvg8cOcpK8ZpIhtWwRYqSSqTbXS0knVmhaJDoQGONYRIx
kxEhrb4Wzj7aEPQI1CNZi300MU4qSTeWylt6vtdAZIc5xPMqvAHaRCpDJlrM714/n5vIgLXmqEM5
BYsgM9a3806oBy9wfHviHtSRmqJDOoiVALcrd/PKeOJZbeJDxyhDEkgpIKkQyZvJyd0xGnha2Xj4
aSDIkGHFEBzNs/S+nKb1Jo8kgoiG/THThAdSA3rs/Lp+fuxjG2MuJBZn0QFvNukhnL1yrPXgh1JB
2SGEA7Y0S1leY5X6ViqCM7Wv0KS928bSAWvED1OV3pWVFaY5HfAW6ZSQZYWz4SBf0xa8WQh0uQHG
aqrTridoxsuCLTztIh48pugMYQGXh1hEjHN3QGtdN0BbVNNw5Egz6uoI045ZWpILX33rPKRDNCHU
Ly2QqOptzj5EhH//tIPtIPtekFpJI+aAyf0LuSKcKEh4Pfv7gA==
