#!/bin/sh
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0
#
# ubsan-summary.json -- JSON shellball generated by scripts/ci/jsonball.py; do not edit.
# Regenerate with: python3 scripts/ci/jsonball.py pack <input.json>
#
# The JSON payload is embedded below the __JSONBALL_PAYLOAD__ marker as base64 text
# (compression: gzip). Run with no arguments or "help" for usage.

set -eu

PN_NAME="ubsan-summary.json"
PN_COMPRESSION="gzip"
PN_DECODE_CMD="base64 -d | gzip -dc"
PN_TOOLS="sed base64 gzip"
PN_SHA256="8436b781b654f355420e303dedb3245d900154d0f09719c25795eb4d6647d5a5"
PN_SIZE=11013
PN_ENCODED_SIZE=895
PN_MIN_COMPRESS_SIZE=1024
PN_COMMIT="06465a9cc4f7ec3555703615e3e0b8138239d23e"
PN_CREATED_AT="2026-08-02T17:36:39Z"

payload() {
	sed -e '1,/^__JSONBALL_PAYLOAD__$/d' "$0"
}

decode() {
	payload | base64 -d | gzip -dc
}

usage() {
	cat <<EOF
usage: sh $0 <command> [args]

$PN_NAME: self-extracting JSON archive ($PN_SIZE bytes of JSON,
$PN_ENCODED_SIZE bytes encoded, compression: $PN_COMPRESSION).

commands:
  cat            decode the JSON to stdout
  extract [DIR]  decode to DIR (default: a new temporary directory);
                 prints the path of the extracted file
  query EXPR     run "jq EXPR" against the decoded JSON (requires jq)
  commit         print the commit the data was collected from
  created        print the collection timestamp
  sha256         print the expected sha256 of the decoded JSON
  tools          print the decode pipeline and the tools it requires
  info           print all embedded metadata
  verify         decode and check against the embedded sha256
  help           show this help
EOF
}

cmd="${1:-help}"
[ $# -gt 0 ] && shift

case "$cmd" in
cat)
	decode
	;;
extract)
	dir="${1:-$(mktemp -d)}"
	mkdir -p "$dir"
	decode > "$dir/$PN_NAME"
	echo "$dir/$PN_NAME"
	;;
query)
	decode | jq "$@"
	;;
commit)
	echo "$PN_COMMIT"
	;;
created)
	echo "$PN_CREATED_AT"
	;;
sha256)
	echo "$PN_SHA256"
	;;
tools)
	echo "decode pipeline: sed -e '1,/^__JSONBALL_PAYLOAD__$/d' $0 | $PN_DECODE_CMD"
	echo "required tools: $PN_TOOLS"
	;;
info)
	echo "name: $PN_NAME"
	echo "compression: $PN_COMPRESSION"
	echo "decode: $PN_DECODE_CMD"
	echo "tools: $PN_TOOLS"
	echo "sha256: $PN_SHA256"
	echo "size: $PN_SIZE"
	echo "encoded-size: $PN_ENCODED_SIZE"
	echo "min-compress-size: $PN_MIN_COMPRESS_SIZE"
	echo "commit: $PN_COMMIT"
	echo "created-at: $PN_CREATED_AT"
	;;
verify)
	actual=$(decode | sha256sum | cut -d' ' -f1)
	if [ "$actual" = "$PN_SHA256" ]; then
		echo "OK: $PN_NAME sha256 $actual"
	else
		echo "FAIL: $PN_NAME sha256 $actual != $PN_SHA256" >&2
		exit 1
	fi
	;;
help | *)
	usage
	;;
esac
exit 0
__JSONBALL_PAYLOAD__
H4sIAAAAAAACA+2azY7aMBCA7zwFynlXhYSEhefoqVU1Ms4kserYkccJrFa8ex0CNFR7cVH2EPkE
mbHN8PlnZjz5WCyXUWl021C0X364J/fM6F3xymilWwKh7wqnIo6KGaFpJHTi9kBMPYickOtWWfpH
6uQNI8LcydOR/Pwy7lowITGHolXcCq36QX7++qxFI5kttKk/afGgerRAMSs6BBL1t+FrNNI/jkKW
2bYf4mb2XXlejD+v9kcHZoxAQ5NB28wQGgfJVAnUNo02FkyA5wdPHABPNlDzoSY1/w2EEi+WB3Ye
7HLsBMcpPcMcqWGHyhb5ZMzWM2RW5FCXdTjZvJg5s6A/3YQqAzhfcPROFusQ8npwq5GIlQh96ynX
3CzZtVZAYzR3DCcDl8wQnEJ71Caccb7YtII+x2IHiZOBi2cIrtEkTmCQSSvq/idKxWTI8v0RDg4W
cubWICMMBJ8lGK5LvBia4yU4DlvXBxphzZpKGwzYvLAFL/G/zCa90ExnyU2VLn+dOpeYJbpGqImd
whyx2cqFwzmQyydYLjgQmg5NyGK9ERJMGgmnMwYXyl6e3FzyOmFxOpshshMJYHnHFHfW3S4AQhXn
WYJw3cKBpCfJAPBJgF8UKW/mis+6ZVeHaoU3t+HaTuqyDFULf3wh4vNkt7j+h8gddJ2D5Lzv31c8
ua5r0YOMVtkmS9mO802xRZ6kabpdJdk6xQRXh7d18hYnuzxOMHoZ9wSqtBn3v6vdLFnHgV2U8SrO
Xldvr6v4+3q7T7J9svtxa+nM6ivufTN7FG5vGBhm7ZaVV8xc5rtBbi/To1opH5UG+2LW4K2umr4q
WEh9BNMqaI3sx4/uLIhXWDNweSoNb32tF+fFH1Co1QIFKwAA
